export type DestinationFact = {
  label: string
  value: string
}

export type VisitedDestination = {
  slug: string
  name: string
  title: string
  eyebrow: string
  country: string
  region: string
  image: string
  description: string
  intro: string
  mood: string
  bestFor: string
  visited: string
  mapLabel: string
  countryIds: string[]
  marker: [number, number]
  mapScale: number
  mapCenter: [number, number]
  highlights: string[]
  places: string[]
  gallery: string[]
}

export const visitedDestinations: VisitedDestination[] = [
  {
    slug: 'peru',
    name: 'Peru',
    title: 'Peru in lagen van stad, bergen en oude verhalen',
    eyebrow: 'Overview',
    country: 'Peru',
    region: 'Zuid-Amerika',
    image: '/media/cusco-12-scaled.webp',
    description: 'Cusco, Andeslicht en plekken waar geschiedenis nog heel dichtbij voelt.',
    intro:
      'Peru is een bestemming waar het landschap voortdurend verandert: koloniale straten, hoge bergpassen, markten, ruïnes en uitzichten die je stil maken.',
    mood: 'Andes, cultuur en fotografie',
    bestFor: 'Machu Picchu, Cusco en lokale markten',
    visited: 'Peru',
    mapLabel: 'PERU',
    countryIds: ['604'],
    marker: [-75.0152, -9.19],
    mapScale: 620,
    mapCenter: [-76, -10],
    highlights: ['Cusco als uitvalsbasis', 'Machu Picchu en de Sacred Valley', 'Fotogenieke markten en berglicht'],
    places: ['Lima', 'Cusco', 'Sacred Valley', 'Machu Picchu'],
    gallery: ['/media/cusco-12-scaled.webp', '/media/DSC_3016-copy-scaled.webp', '/media/image3300.jpg'],
  },
  {
    slug: 'maleisie',
    name: 'Maleisië',
    title: 'Maleisië tussen jungle, stad en eilandrust',
    eyebrow: 'Overview',
    country: 'Maleisië',
    region: 'Azië',
    image: '/media/maleisie-7-scaled.webp',
    description: 'Kuala Lumpur, Batu Caves, theevelden en eilanden met een rustig tempo.',
    intro:
      'Maleisië voelt als meerdere reizen in één: drukke foodcourts, groene hooglanden, kleurrijke tempels en stranden waar de dag vanzelf vertraagt.',
    mood: 'Food, jungle en eilanden',
    bestFor: 'Streetfood, Batu Caves en Langkawi',
    visited: 'Maleisië en Langkawi',
    mapLabel: 'MALEISIË',
    countryIds: ['458'],
    marker: [101.9758, 4.2105],
    mapScale: 680,
    mapCenter: [103, 4],
    highlights: ['Kuala Lumpur en Batu Caves', 'Cameron Highlands', 'Langkawi als eilandstop'],
    places: ['Kuala Lumpur', 'Batu Caves', 'Cameron Highlands', 'Langkawi'],
    gallery: ['/media/maleisie-7-scaled.webp', '/media/Batucaves-6-scaled.webp', '/media/langkawi-scaled.webp'],
  },
  {
    slug: 'langkawi',
    name: 'Langkawi',
    title: 'Langkawi voor uitzicht, zee en een rustiger ritme',
    eyebrow: 'Island stop',
    country: 'Maleisië',
    region: 'Azië',
    image: '/media/langkawi-scaled.webp',
    description: 'Een eilandstop met uitzichtpunten, kustwegen en zachte avonden.',
    intro:
      'Langkawi is het rustige hoofdstuk van Maleisië: groen, water, kleine wegen en plekken waar je vooral wilt blijven hangen rond zonsondergang.',
    mood: 'Eiland, natuur en rust',
    bestFor: 'Stranden, viewpoints en fotografie',
    visited: 'Langkawi',
    mapLabel: 'LANGKAWI',
    countryIds: ['458'],
    marker: [99.8, 6.35],
    mapScale: 760,
    mapCenter: [101, 5],
    highlights: ['Uitzicht vanaf hoger gelegen punten', 'Kust en eilandroutes', 'Zachte avondlucht voor fotografie'],
    places: ['Langkawi', 'Pantai Cenang', 'Eilandroutes'],
    gallery: ['/media/langkawi-scaled.webp', '/media/langkawi-scaled-800x532.webp', '/media/ombakvilla-scaled.jpg'],
  },
  {
    slug: 'thailand',
    name: 'Thailand',
    title: 'Thailand met Bangkok als eerste indruk',
    eyebrow: 'Overview',
    country: 'Thailand',
    region: 'Azië',
    image: '/media/bangkok-scaled.webp',
    description: 'Bangkok, tempels, markten en drukte die langzaam logisch wordt.',
    intro:
      'Thailand staat hier vooral voor Bangkok: een stad vol contrast, streetfood, tempels, verkeer en kleine momenten tussen de drukte door.',
    mood: 'Stad, tempels en food',
    bestFor: 'Bangkok en dagtrips',
    visited: 'Bangkok',
    mapLabel: 'THAILAND',
    countryIds: ['764'],
    marker: [100.5018, 13.7563],
    mapScale: 760,
    mapCenter: [101, 14],
    highlights: ['Bangkok streetfood', 'Tempels en rivierleven', 'Ayutthaya als dagtrip'],
    places: ['Bangkok', 'Ayutthaya'],
    gallery: ['/media/bangkok-scaled.webp', '/media/Ayuthayya-1-2-scaled.webp', '/media/Ayuthayya-1-4-scaled.webp'],
  },
  {
    slug: 'bangkok',
    name: 'Bangkok',
    title: 'Bangkok in tempels, verkeer en avondlicht',
    eyebrow: 'City stop',
    country: 'Thailand',
    region: 'Azië',
    image: '/media/bangkok-scaled.webp',
    description: 'Een stad die veel tegelijk is: druk, warm, lekker en fotogeniek.',
    intro:
      'Bangkok is geen plek die je in één wandeling begrijpt. Juist de mix van tempels, markten, food en chaos maakt het een bestemming die blijft trekken.',
    mood: 'Streetfood en stadsenergie',
    bestFor: 'Tempels, markten en avondroutes',
    visited: 'Bangkok',
    mapLabel: 'BANGKOK',
    countryIds: ['764'],
    marker: [100.5018, 13.7563],
    mapScale: 840,
    mapCenter: [101, 14],
    highlights: ['Streetfood in de avond', 'Tempels langs de rivier', 'Contrasten tussen rust en drukte'],
    places: ['Bangkok', 'Chao Phraya', 'Tempelroutes'],
    gallery: ['/media/bangkok-scaled.webp', '/media/Ayuthayya-1-9-scaled.webp', '/media/Ayuthayya-1-2-scaled.webp'],
  },
  {
    slug: 'indonesie',
    name: 'Indonesië',
    title: 'Indonesië van Java tot Lombok',
    eyebrow: 'Overview',
    country: 'Indonesië',
    region: 'Azië',
    image: '/media/DJI_20240517152816_0082_D-scaled.webp',
    description: 'Java, Bali en Lombok met rijstvelden, vulkanen en eilandroutes.',
    intro:
      'Indonesië is groot en gelaagd. Deze pagina bundelt de plekken waar ik ben geweest: Java, Bali en Lombok, elk met een eigen tempo en sfeer.',
    mood: 'Eilanden, rijstvelden en vulkanen',
    bestFor: 'Java, Bali en Lombok',
    visited: 'Java, Bali en Lombok',
    mapLabel: 'INDONESIË',
    countryIds: ['360'],
    marker: [113.9213, -7.8],
    mapScale: 700,
    mapCenter: [116, -4],
    highlights: ['Java als cultureel startpunt', 'Bali voor rijstvelden en kust', 'Lombok voor rustiger eilandgevoel'],
    places: ['Java', 'Bali', 'Lombok'],
    gallery: ['/media/DJI_20240517152816_0082_D-scaled.webp', '/media/IMG_2243-scaled.jpeg', '/media/image896.jpg'],
  },
  {
    slug: 'java',
    name: 'Java',
    title: 'Java als cultureel hart van Indonesië',
    eyebrow: 'Island stop',
    country: 'Indonesië',
    region: 'Azië',
    image: '/media/DJI_20240517152816_0082_D-scaled.webp',
    description: 'Steden, tempels, treinroutes en landschappen met veel lagen.',
    intro:
      'Java voelt intens en rijk: drukke steden, tempels, treinroutes en landschappen die steeds weer veranderen.',
    mood: 'Cultuur en routes',
    bestFor: 'Tempels, steden en landschappen',
    visited: 'Java',
    mapLabel: 'JAVA',
    countryIds: ['360'],
    marker: [110.7122, -7.6145],
    mapScale: 760,
    mapCenter: [112, -7],
    highlights: ['Treinroutes door Java', 'Tempels en lokale stops', 'Fotografie onderweg'],
    places: ['Java', 'Yogyakarta', 'Tempelroutes'],
    gallery: ['/media/DJI_20240517152816_0082_D-scaled.webp', '/media/image896.jpg', '/media/IMG_2243-scaled.jpeg'],
  },
  {
    slug: 'bali',
    name: 'Bali',
    title: 'Bali voorbij alleen het perfecte plaatje',
    eyebrow: 'Island stop',
    country: 'Indonesië',
    region: 'Azië',
    image: '/media/IMG_2243-scaled.jpeg',
    description: 'Rijstvelden, kust, tempels en rustige momenten tussen bekende plekken.',
    intro:
      'Bali is bekend, maar tussen de bekende stops zitten nog genoeg rustige momenten: rijstvelden, kleine wegen, tempels en licht dat alles zacht maakt.',
    mood: 'Rijstvelden en kust',
    bestFor: 'Uitzichten, tempels en fotografie',
    visited: 'Bali',
    mapLabel: 'BALI',
    countryIds: ['360'],
    marker: [115.092, -8.3405],
    mapScale: 800,
    mapCenter: [116, -7],
    highlights: ['Rijstvelden in zacht licht', 'Tempels en kustplekken', 'Rustige routes buiten de drukte'],
    places: ['Bali', 'Rijstvelden', 'Kustroutes'],
    gallery: ['/media/IMG_2243-scaled.jpeg', '/media/DJI_20240517152816_0082_D-scaled.webp', '/media/image1086.jpg'],
  },
  {
    slug: 'lombok',
    name: 'Lombok',
    title: 'Lombok met meer ruimte en minder haast',
    eyebrow: 'Island stop',
    country: 'Indonesië',
    region: 'Azië',
    image: '/media/DJI_20240517152816_0082_D-scaled.webp',
    description: 'Een rustiger eilandgevoel met kust, heuvels en open wegen.',
    intro:
      'Lombok voelt ruimer en rustiger dan veel bekende eilandstops. Het is een plek voor kustwegen, open uitzichten en langzamer reizen.',
    mood: 'Rust, kust en ruimte',
    bestFor: 'Roadtrips en eilandgevoel',
    visited: 'Lombok',
    mapLabel: 'LOMBOK',
    countryIds: ['360'],
    marker: [116.3249, -8.65],
    mapScale: 800,
    mapCenter: [116, -7],
    highlights: ['Kustwegen', 'Rustiger eilandtempo', 'Uitzichten en open landschappen'],
    places: ['Lombok', 'Kustroutes', 'Heuvels'],
    gallery: ['/media/DJI_20240517152816_0082_D-scaled.webp', '/media/image896.jpg', '/media/IMG_2243-scaled.jpeg'],
  },
  {
    slug: 'vietnam',
    name: 'Vietnam',
    title: 'Vietnam van stadsgeluid naar groene routes',
    eyebrow: 'Overview',
    country: 'Vietnam',
    region: 'Azië',
    image: '/media/1920x540.webp',
    description: 'Lange routes, drukke steden, kust en groen bergland.',
    intro:
      'Vietnam is een land van beweging: scooters, markten, lange afstanden en landschappen die van stad naar kust naar bergen verschuiven.',
    mood: 'Routes, food en landschap',
    bestFor: 'Steden, kust en noordelijke natuur',
    visited: 'Vietnam',
    mapLabel: 'VIETNAM',
    countryIds: ['704'],
    marker: [107.8333, 16.1667],
    mapScale: 760,
    mapCenter: [107, 16],
    highlights: ['Steden vol energie', 'Kust en groene routes', 'Veel streetfood en kleine stops'],
    places: ['Vietnam', 'Stadsroutes', 'Kust en bergen'],
    gallery: ['/media/1920x540.webp', '/media/image850.jpg', '/media/image881.jpg'],
  },
  {
    slug: 'japan',
    name: 'Japan',
    title: 'Japan op het mainland, van stad tot bergdorp',
    eyebrow: 'Overview',
    country: 'Japan',
    region: 'Azië',
    image: '/media/Shirakawago-3.webp',
    description: 'Mainland Japan met steden, dorpen, bergen en stille details.',
    intro:
      'Japan is precies en verrassend tegelijk: grote steden, kleine rituelen, bergdorpen en plekken waar zelfs de stilte ontworpen lijkt.',
    mood: 'Steden, dorpen en details',
    bestFor: 'Mainland Japan, zonder Okinawa',
    visited: 'Japan mainland',
    mapLabel: 'JAPAN',
    countryIds: ['392'],
    marker: [138.2529, 36.2048],
    mapScale: 650,
    mapCenter: [138, 37],
    highlights: ['Shirakawa-go en bergdorpen', 'Stedelijke ritmes', 'Details in eten, stations en straten'],
    places: ['Mainland Japan', 'Shirakawa-go', 'Stadsroutes'],
    gallery: ['/media/Shirakawago-3.webp', '/media/Shirakawago-3-800x450.webp', '/media/image3344.jpg'],
  },
  {
    slug: 'singapore',
    name: 'Singapore',
    title: 'Singapore als compacte stad vol contrast',
    eyebrow: 'City stop',
    country: 'Singapore',
    region: 'Azië',
    image: '/media/Franksunset-scaled.webp',
    description: 'Skyline, groen, foodcourts en een stad die strak en warm tegelijk voelt.',
    intro:
      'Singapore is compact, maar vol contrast: glanzende skyline, groen, hawker food en wijken waar veel culturen samenkomen.',
    mood: 'Stad, food en skyline',
    bestFor: 'Foodcourts en architectuur',
    visited: 'Singapore',
    mapLabel: 'SINGAPORE',
    countryIds: ['702'],
    marker: [103.8198, 1.3521],
    mapScale: 780,
    mapCenter: [104, 2],
    highlights: ['Hawker food', 'Skyline en stadsparken', 'Compacte routes te voet'],
    places: ['Singapore', 'Hawker centres', 'Skyline'],
    gallery: ['/media/Franksunset-scaled.webp', '/media/image833.jpg', '/media/image929.jpg'],
  },
  {
    slug: 'verenigde-staten',
    name: 'Verenigde Staten',
    title: 'Verenigde Staten van citytrip tot roadtrip',
    eyebrow: 'Overview',
    country: 'Verenigde Staten',
    region: 'Noord-Amerika',
    image: '/media/newyork-1-scaled.webp',
    description: 'New York, Florida en roadtriproutes door grote landschappen.',
    intro:
      'De Verenigde Staten staan op Meet the Locals voor contrast: New Yorkse energie, Florida-zon en roadtrips waar de afstanden onderdeel van de reis zijn.',
    mood: 'Steden en roadtrips',
    bestFor: 'New York, Florida, Westkust en Route 66',
    visited: 'New York, Florida, Westkust en Route 66',
    mapLabel: 'VERENIGDE STATEN',
    countryIds: ['840'],
    marker: [-98.5795, 39.8283],
    mapScale: 420,
    mapCenter: [-98, 38],
    highlights: ['New York als stedentrip', 'Florida voor zon en kust', 'Westkust en Route 66 als roadtripgevoel'],
    places: ['New York', 'Florida', 'Westkust', 'Route 66'],
    gallery: ['/media/newyork-1-scaled.webp', '/media/newyork-1-scaled-800x532.jpg', '/media/kellys-scaled.jpg'],
  },
  {
    slug: 'new-york',
    name: 'New York',
    title: 'New York in lagen van straten, licht en energie',
    eyebrow: 'City stop',
    country: 'Verenigde Staten',
    region: 'Noord-Amerika',
    image: '/media/newyork-1-scaled.webp',
    description: 'Een stad die je niet hoeft uit te leggen, maar wel steeds opnieuw kunt bekijken.',
    intro:
      'New York is groot, direct en fotogeniek. De stad werkt vooral goed als je niet alleen naar highlights kijkt, maar naar straten, ritmes en licht.',
    mood: 'Stad, fotografie en eten',
    bestFor: 'Straten, skyline en foodspots',
    visited: 'New York',
    mapLabel: 'NEW YORK',
    countryIds: ['840'],
    marker: [-74.006, 40.7128],
    mapScale: 520,
    mapCenter: [-87, 39],
    highlights: ['Straatfotografie', 'Skyline en buurten', 'Foodspots en kleine routes'],
    places: ['New York City', 'Manhattan', 'Brooklyn'],
    gallery: ['/media/newyork-1-scaled.webp', '/media/newyork-1-scaled-800x532.jpg', '/media/image1086.jpg'],
  },
  {
    slug: 'florida',
    name: 'Florida',
    title: 'Florida met zon, routes en kustgevoel',
    eyebrow: 'State stop',
    country: 'Verenigde Staten',
    region: 'Noord-Amerika',
    image: '/media/kellys-scaled.jpg',
    description: 'Zon, kustwegen en een relaxter stuk Verenigde Staten.',
    intro:
      'Florida voelt lichter en losser: kust, zon, routes en plekken waar de reis minder om planning en meer om onderweg zijn draait.',
    mood: 'Zon, kust en roadtrip',
    bestFor: 'Kustroutes en warme avonden',
    visited: 'Florida',
    mapLabel: 'FLORIDA',
    countryIds: ['840'],
    marker: [-81.5158, 27.6648],
    mapScale: 520,
    mapCenter: [-87, 31],
    highlights: ['Kustwegen', 'Zon en open routes', 'Roadtripgevoel'],
    places: ['Florida', 'Kust', 'Roadtriproutes'],
    gallery: ['/media/kellys-scaled.jpg', '/media/kellys-scaled-800x533.jpg', '/media/newyork-1-scaled.webp'],
  },
  {
    slug: 'marokko',
    name: 'Marokko',
    title: 'Marokko in kleur, warmte en ritme',
    eyebrow: 'Overview',
    country: 'Marokko',
    region: 'Afrika',
    image: '/media/woestijn-9-scaled.webp',
    description: 'Marrakesh, warm licht en details die overal om aandacht vragen.',
    intro:
      'Marokko is een bestemming van kleur en ritme: markten, binnenplaatsen, warm licht en geuren die meteen onderdeel van je herinnering worden.',
    mood: 'Kleur, medina en woestijnlicht',
    bestFor: 'Marrakesh en fotografie',
    visited: 'Marrakesh',
    mapLabel: 'MAROKKO',
    countryIds: ['504'],
    marker: [-7.9811, 31.6295],
    mapScale: 620,
    mapCenter: [-6, 31],
    highlights: ['Marrakesh', 'Medina-details', 'Warm licht voor fotografie'],
    places: ['Marrakesh', 'Medina', 'Woestijnsfeer'],
    gallery: ['/media/woestijn-9-scaled.webp', '/media/woestijn-3-scaled.jpeg', '/media/woestijn-3-scaled-1.jpeg'],
  },
  {
    slug: 'colombia',
    name: 'Colombia',
    title: 'Colombia met verhalen tussen natuur en cultuur',
    eyebrow: 'Overview',
    country: 'Colombia',
    region: 'Zuid-Amerika',
    image: '/media/Dansenmaloca-scaled.webp',
    description: 'Een bestemming met veel kleur, natuur en menselijke verhalen.',
    intro:
      'Colombia staat hier voor ontmoetingen, natuur en cultuur. Een bestemming waar de reis niet alleen in landschappen zit, maar vooral in verhalen.',
    mood: 'Natuur, mensen en cultuur',
    bestFor: 'Verhalen en fotografie',
    visited: 'Colombia',
    mapLabel: 'COLOMBIA',
    countryIds: ['170'],
    marker: [-74.2973, 4.5709],
    mapScale: 620,
    mapCenter: [-74, 5],
    highlights: ['Lokale verhalen', 'Natuur en ritme', 'Fotografie met mensen en context'],
    places: ['Colombia', 'Lokale gemeenschappen', 'Natuurgebieden'],
    gallery: ['/media/Dansenmaloca-scaled.webp', '/media/Dansenmaloca-scaled-800x532.webp', '/media/image3344.jpg'],
  },
  {
    slug: 'italie',
    name: 'Italië',
    title: 'Italië van noord naar zuid in smaak en landschap',
    eyebrow: 'Overview',
    country: 'Italië',
    region: 'Europa',
    image: '/media/woestijn-9-scaled-800x532.jpg',
    description: 'Como, Puglia, Emilia-Romagna, Toscane, Marche en Calabria.',
    intro:
      'Italië is op deze site een verzameling routes: van meren en dorpen in het noorden tot eten, kust en trage wegen verder naar het zuiden.',
    mood: 'Food, dorpen en routes',
    bestFor: 'Roadtrips en regionale keuken',
    visited: 'Como, Puglia, Emilia-Romagna, Toscane, Marche en Calabria',
    mapLabel: 'ITALIË',
    countryIds: ['380'],
    marker: [12.5674, 41.8719],
    mapScale: 720,
    mapCenter: [12, 42],
    highlights: ['Como en Lombardia', 'Puglia en zuidelijke sfeer', 'Emilia-Romagna en food'],
    places: ['Como', 'Puglia', 'Emilia-Romagna', 'Toscane', 'Marche', 'Calabria'],
    gallery: ['/media/woestijn-9-scaled-800x532.jpg', '/media/Franksunset-scaled.webp', '/media/kellys-scaled.jpg'],
  },
  {
    slug: 'spanje',
    name: 'Spanje',
    title: 'Spanje met Sevilla als warme stadsstop',
    eyebrow: 'Overview',
    country: 'Spanje',
    region: 'Europa',
    image: '/media/Franksunset-scaled.webp',
    description: 'Zon, stad, eten en een tempo dat vanzelf vertraagt.',
    intro:
      'Spanje draait hier om warme straten, eten, pleinen en dat relaxte ritme waarin een stad pas later op de dag echt wakker lijkt te worden.',
    mood: 'Stad, zon en food',
    bestFor: 'Sevilla en stedelijke routes',
    visited: 'Sevilla',
    mapLabel: 'SPANJE',
    countryIds: ['724'],
    marker: [-5.9845, 37.3891],
    mapScale: 680,
    mapCenter: [-4, 40],
    highlights: ['Sevilla', 'Avondlicht', 'Eten en pleinen'],
    places: ['Sevilla', 'Stadsroutes'],
    gallery: ['/media/Franksunset-scaled.webp', '/media/image833.jpg', '/media/woestijn-3-scaled.jpeg'],
  },
  {
    slug: 'frankrijk',
    name: 'Frankrijk',
    title: 'Frankrijk dichtbij, maar nooit hetzelfde',
    eyebrow: 'Overview',
    country: 'Frankrijk',
    region: 'Europa',
    image: '/media/kellys-scaled-800x533.jpg',
    description: 'Parijs en routes waar eten, straten en sfeer samenkomen.',
    intro:
      'Frankrijk is dichtbij, maar verandert snel per regio. Op deze pagina staat vooral de combinatie van stadsritme, eten en sfeer centraal.',
    mood: 'Stad, eten en sfeer',
    bestFor: 'Parijs en korte trips',
    visited: 'Parijs',
    mapLabel: 'FRANKRIJK',
    countryIds: ['250'],
    marker: [2.3522, 48.8566],
    mapScale: 650,
    mapCenter: [2, 46],
    highlights: ['Parijs', 'Straten en cafés', 'Korte routes dichtbij huis'],
    places: ['Parijs', 'Cafés', 'Stadsroutes'],
    gallery: ['/media/kellys-scaled-800x533.jpg', '/media/Franksunset-scaled.webp', '/media/image3344.jpg'],
  },
  {
    slug: 'duitsland',
    name: 'Duitsland',
    title: 'Duitsland net over de grens en verder',
    eyebrow: 'Overview',
    country: 'Duitsland',
    region: 'Europa',
    image: '/media/Shirakawago-3.webp',
    description: 'Hunsrück, Esslingen en plekken die dichtbij toch anders voelen.',
    intro:
      'Duitsland is ideaal voor korte routes met veel afwisseling: vakwerk, heuvels, steden en regio’s die je makkelijk over het hoofd ziet.',
    mood: 'Korte trips en regio’s',
    bestFor: 'Hunsrück en Esslingen am Neckar',
    visited: 'Hunsrück en Esslingen am Neckar',
    mapLabel: 'DUITSLAND',
    countryIds: ['276'],
    marker: [9.3059, 48.7395],
    mapScale: 680,
    mapCenter: [10, 51],
    highlights: ['Hunsrück', 'Esslingen am Neckar', 'Dichtbij maar anders'],
    places: ['Hunsrück', 'Esslingen am Neckar'],
    gallery: ['/media/Shirakawago-3.webp', '/media/image3344.jpg', '/media/kellys-scaled.jpg'],
  },
  {
    slug: 'nederland',
    name: 'Nederland',
    title: 'Nederland als dichtbij-bestemming',
    eyebrow: 'Overview',
    country: 'Nederland',
    region: 'Europa',
    image: '/media/DSC_3016-copy-scaled.webp',
    description: 'Dichtbij huis, met plekken die je snel over het hoofd ziet.',
    intro:
      'Ook dichtbij huis zijn er plekken die voelen als een kleine reis. Nederland krijgt hier ruimte voor lokale adressen, korte routes en fotografie om de hoek.',
    mood: 'Dichtbij en lokaal',
    bestFor: 'Korte trips en lokale adressen',
    visited: 'Nederland',
    mapLabel: 'NEDERLAND',
    countryIds: ['528'],
    marker: [5.2913, 52.1326],
    mapScale: 760,
    mapCenter: [5, 52],
    highlights: ['Lokale adressen', 'Korte routes', 'Fotografie dichtbij huis'],
    places: ['Nederland', 'Lokale plekken'],
    gallery: ['/media/DSC_3016-copy-scaled.webp', '/media/kellys-scaled.jpg', '/media/image3344.jpg'],
  },
  {
    slug: 'ierland',
    name: 'Ierland',
    title: 'Ierland in groen, kust en pubwarmte',
    eyebrow: 'Overview',
    country: 'Ierland',
    region: 'Europa',
    image: '/media/image3344.jpg',
    description: 'Groene landschappen, ruige kust en plekken met karakter.',
    intro:
      'Ierland heeft een directe sfeer: groen, kust, wind en warme plekken waar je na een dag buiten wilt blijven hangen.',
    mood: 'Kust, groen en pubs',
    bestFor: 'Roadtrips en ruige natuur',
    visited: 'Ierland',
    mapLabel: 'IERLAND',
    countryIds: ['372'],
    marker: [-8.2439, 53.4129],
    mapScale: 700,
    mapCenter: [-8, 53],
    highlights: ['Groene landschappen', 'Kustwegen', 'Warme pubcultuur'],
    places: ['Ierland', 'Kustroutes', 'Groene landschappen'],
    gallery: ['/media/image3344.jpg', '/media/image3344-800x449.jpg', '/media/kellys-scaled.jpg'],
  },
  {
    slug: 'nieuw-zeeland',
    name: 'Nieuw-Zeeland',
    title: 'Nieuw-Zeeland als grote natuurroute',
    eyebrow: 'Overview',
    country: 'Nieuw-Zeeland',
    region: 'Oceanië',
    image: '/media/woestijn-3-scaled-1.jpeg',
    description: 'Roadtripgevoel, grote natuur en landschappen die blijven hangen.',
    intro:
      'Nieuw-Zeeland is een bestemming voor grote natuur en lange routes. Het soort plek waar de weg zelf vaak net zo belangrijk is als de stop.',
    mood: 'Natuur en roadtrip',
    bestFor: 'Landschappen en routes',
    visited: 'Nieuw-Zeeland',
    mapLabel: 'NIEUW-ZEELAND',
    countryIds: ['554'],
    marker: [174.886, -40.9006],
    mapScale: 540,
    mapCenter: [173, -41],
    highlights: ['Roadtriproutes', 'Grote natuur', 'Fotografie onderweg'],
    places: ['Nieuw-Zeeland', 'Roadtriproutes', 'Natuurgebieden'],
    gallery: ['/media/woestijn-3-scaled-1.jpeg', '/media/woestijn-3-scaled.jpeg', '/media/Franksunset-scaled.webp'],
  },
]

export const destinationIndex = visitedDestinations

export function getVisitedDestination(slug: string): VisitedDestination | undefined {
  return visitedDestinations.find((destination) => destination.slug === slug)
}
