/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    posts: Post;
    news: News;
    stories: Story;
    destinations: Destination;
    'photo-spots': PhotoSpot;
    'photography-posts': PhotographyPost;
    'photo-galleries': PhotoGallery;
    categories: Category;
    tags: Tag;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    posts: PostsSelect<false> | PostsSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    stories: StoriesSelect<false> | StoriesSelect<true>;
    destinations: DestinationsSelect<false> | DestinationsSelect<true>;
    'photo-spots': PhotoSpotsSelect<false> | PhotoSpotsSelect<true>;
    'photography-posts': PhotographyPostsSelect<false> | PhotographyPostsSelect<true>;
    'photo-galleries': PhotoGalleriesSelect<false> | PhotoGalleriesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  heroImage: number | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  excerpt: string;
  publishedDate: string;
  destinations?: (number | Destination)[] | null;
  categories?: (number | Category)[] | null;
  tags?: (number | Tag)[] | null;
  /**
   * Werelddeel waar deze blog over gaat. Voedt het werelddeelfilter op de blogpagina.
   */
  werelddeel?: ('europe' | 'asia' | 'north-america' | 'south-america' | 'africa' | 'oceania' | 'middle-east') | null;
  /**
   * Eén of meer thema's. Voeden het themafilter op de blogpagina.
   */
  thema?:
    | ('reisfotografie' | 'food' | 'accommodaties' | 'reisverhalen-routes' | 'reistips-praktisch' | 'natuur-buiten')[]
    | null;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  mapPoints?:
    | {
        label?: string | null;
        latitude: number;
        longitude: number;
        id?: string | null;
      }[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  status?: ('draft' | 'published' | 'scheduled') | null;
  /**
   * Plak reisnotities of steekwoorden. Klik op "Genereer concept" om een AI-draft te genereren.
   */
  aiDraft?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  /**
   * Wordt automatisch uitgelezen bij het uploaden. Vul handmatig aan als een veld leeg blijft.
   */
  exif?: {
    camera?: string | null;
    lens?: string | null;
    aperture?: string | null;
    shutterSpeed?: string | null;
    iso?: string | null;
    focalLength?: string | null;
    takenAt?: string | null;
    /**
     * Uit de foto gelezen. Wordt gebruikt om de pin te plaatsen.
     */
    latitude?: number | null;
    longitude?: number | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destinations".
 */
export interface Destination {
  id: number;
  name: string;
  slug: string;
  level?: ('land' | 'regio' | 'gebied' | 'stad') | null;
  /**
   * Bovenliggende bestemming, bijv. Italië voor Apulië.
   */
  parent?: (number | null) | Destination;
  region: 'europe' | 'asia' | 'north-america' | 'south-america' | 'africa' | 'oceania' | 'middle-east';
  heroImage: number | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Kleine koptekst boven de titel, bijv. "Regio" of "Overview".
   */
  eyebrow?: string | null;
  /**
   * Uitgebreide paginatitel voor de detailpagina.
   */
  title?: string | null;
  /**
   * Lead-tekst: zichtbaar in de hero van de detailpagina en op kaarten.
   */
  intro?: string | null;
  /**
   * Sfeerwoorden, bijv. "Food, dorpen en routes".
   */
  mood?: string | null;
  /**
   * Uitgebreide beschrijving (optioneel, voor redactionele pagina's).
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Genummerde highlights op de detailpagina.
   */
  highlightList?:
    | {
        text: string;
        /**
         * Optionele foto onderaan het highlight-kaartje.
         */
        photo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Gebieden of plekken als pills op de detailpagina.
   */
  places?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  population?: string | null;
  /**
   * Reistijd, bijv. "±2,5 uur".
   */
  flightHours?: string | null;
  /**
   * ISO 3166-1 alpha-2 code, bijv. JP, FR, PE. Gebruikt voor automatische data-updates via n8n.
   */
  countryCode?: string | null;
  practicalInfo?: {
    budget?: string | null;
    visa?: string | null;
    bestTime?: string | null;
  };
  /**
   * Getoond als scrollende balk onder de fotoslider. Kan automatisch bijgewerkt worden via n8n.
   */
  travelInfo?: {
    /**
     * bijv. Japans, Engels
     */
    language?: string | null;
    /**
     * bijv. Japanse Yen (JPY)
     */
    currency?: string | null;
    /**
     * bijv. Subtropisch, warm en vochtig
     */
    climate?: string | null;
    /**
     * bijv. UTC+9
     */
    timezone?: string | null;
    /**
     * bijv. Type A/B, 110V
     */
    plugType?: string | null;
    /**
     * Reisadvies kleurcode (rijksoverheid.nl).
     */
    safetyLevel?: ('green' | 'yellow' | 'orange' | 'red') | null;
    /**
     * bijv. Normale waakzaamheid, geen specifieke risicos
     */
    safetyNote?: string | null;
    /**
     * bijv. Visumvrij tot 90 dagen voor NL-paspoort
     */
    visaNote?: string | null;
  };
  /**
   * Tekst op de kaart in hoofdletters, bijv. "ITALIË".
   */
  mapLabel?: string | null;
  /**
   * Zoomniveau van de kaart (bijv. 1400).
   */
  mapScale?: number | null;
  mapCenter?: {
    longitude?: number | null;
    latitude?: number | null;
  };
  /**
   * Markerpositie op de kaart.
   */
  coordinates: {
    latitude: number;
    longitude: number;
  };
  /**
   * ISO-3166 numerieke landcodes voor de kaart, bijv. "380" voor Italië.
   */
  countryIds?:
    | {
        countryCode: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  slug: string;
  status: 'draft' | 'published';
  publishedDate: string;
  heroImage?: (number | null) | Media;
  excerpt: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category?: ('bestemming' | 'reistip' | 'branchenieuws' | 'fotografie' | 'overig') | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories".
 */
export interface Story {
  id: number;
  title: string;
  slug: string;
  /**
   * Kleine koptekst boven de titel, bijv. "De smaken van Georgië" of "Drie weken onderweg".
   */
  eyebrow?: string | null;
  heroImage: number | Media;
  /**
   * Korte lead-tekst. Zichtbaar op de kaart én bovenaan het verhaal zelf.
   */
  intro: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  publishedDate: string;
  /**
   * Werelddeel waar dit verhaal over gaat.
   */
  werelddeel?: ('europe' | 'asia' | 'north-america' | 'south-america' | 'africa' | 'oceania' | 'middle-east') | null;
  /**
   * Eén of meer thema's.
   */
  thema?:
    | ('reisfotografie' | 'food' | 'accommodaties' | 'reisverhalen-routes' | 'reistips-praktisch' | 'natuur-buiten')[]
    | null;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Plekken op de interactieve kaart. Elke spot is één eigen foto met locatie en camera-instellingen.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photo-spots".
 */
export interface PhotoSpot {
  id: number;
  /**
   * Naam van de plek, bijvoorbeeld "Zonsopkomst boven Bagan".
   */
  title: string;
  /**
   * Wordt automatisch gevuld op basis van de titel.
   */
  slug?: string | null;
  status?: ('draft' | 'published') | null;
  region?: ('europe' | 'asia' | 'north-america' | 'south-america' | 'africa' | 'oceania' | 'middle-east') | null;
  /**
   * Jouw eigen foto van deze plek. Camera-instellingen worden automatisch uit de foto gelezen.
   */
  photo: number | Media;
  /**
   * Land waar de foto is gemaakt. Wordt ook op de kaart getoond.
   */
  country: string;
  /**
   * Wordt automatisch ingevuld als je foto GPS-data bevat. Anders zelf de coördinaten invullen.
   */
  coordinates: {
    latitude: number;
    longitude: number;
  };
  /**
   * Korte ervaring bij deze plek. Verschijnt op de kaart wanneer je over de pin hovert.
   */
  story?: string | null;
  /**
   * Optioneel. Voegt een "lees het verhaal"-link toe aan de kaartkaart.
   */
  relatedPost?: (number | null) | Post;
  relatedDestination?: (number | null) | Destination;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photography-posts".
 */
export interface PhotographyPost {
  id: number;
  title: string;
  slug: string;
  heroImage: number | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  excerpt: string;
  publishedDate: string;
  photoCategory: 'tips-tutorials' | 'gear-reviews' | 'behind-the-lens' | 'editing-post-processing';
  tags?: (number | Tag)[] | null;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  exifData?: {
    camera?: string | null;
    lens?: string | null;
    settings?: string | null;
  };
  relatedPosts?:
    | (
        | {
            relationTo: 'posts';
            value: number | Post;
          }
        | {
            relationTo: 'photography-posts';
            value: number | PhotographyPost;
          }
      )[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  status?: ('draft' | 'published' | 'scheduled') | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photo-galleries".
 */
export interface PhotoGallery {
  id: number;
  title: string;
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  coverImage: number | Media;
  photos: {
    image: number | Media;
    caption?: string | null;
    location?: string | null;
    exif?: {
      camera?: string | null;
      lens?: string | null;
      focalLength?: string | null;
      aperture?: string | null;
      shutterSpeed?: string | null;
      iso?: string | null;
    };
    id?: string | null;
  }[];
  destination?: (number | null) | Destination;
  gear?: {
    camera?: string | null;
    lenses?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'stories';
        value: number | Story;
      } | null)
    | ({
        relationTo: 'destinations';
        value: number | Destination;
      } | null)
    | ({
        relationTo: 'photo-spots';
        value: number | PhotoSpot;
      } | null)
    | ({
        relationTo: 'photography-posts';
        value: number | PhotographyPost;
      } | null)
    | ({
        relationTo: 'photo-galleries';
        value: number | PhotoGallery;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  heroImage?: T;
  content?: T;
  excerpt?: T;
  publishedDate?: T;
  destinations?: T;
  categories?: T;
  tags?: T;
  werelddeel?: T;
  thema?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  mapPoints?:
    | T
    | {
        label?: T;
        latitude?: T;
        longitude?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  status?: T;
  aiDraft?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  publishedDate?: T;
  heroImage?: T;
  excerpt?: T;
  content?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories_select".
 */
export interface StoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  eyebrow?: T;
  heroImage?: T;
  intro?: T;
  content?: T;
  publishedDate?: T;
  werelddeel?: T;
  thema?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destinations_select".
 */
export interface DestinationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  level?: T;
  parent?: T;
  region?: T;
  heroImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  eyebrow?: T;
  title?: T;
  intro?: T;
  mood?: T;
  description?: T;
  highlightList?:
    | T
    | {
        text?: T;
        photo?: T;
        id?: T;
      };
  places?:
    | T
    | {
        name?: T;
        id?: T;
      };
  population?: T;
  flightHours?: T;
  countryCode?: T;
  practicalInfo?:
    | T
    | {
        budget?: T;
        visa?: T;
        bestTime?: T;
      };
  travelInfo?:
    | T
    | {
        language?: T;
        currency?: T;
        climate?: T;
        timezone?: T;
        plugType?: T;
        safetyLevel?: T;
        safetyNote?: T;
        visaNote?: T;
      };
  mapLabel?: T;
  mapScale?: T;
  mapCenter?:
    | T
    | {
        longitude?: T;
        latitude?: T;
      };
  coordinates?:
    | T
    | {
        latitude?: T;
        longitude?: T;
      };
  countryIds?:
    | T
    | {
        countryCode?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photo-spots_select".
 */
export interface PhotoSpotsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  region?: T;
  photo?: T;
  country?: T;
  coordinates?:
    | T
    | {
        latitude?: T;
        longitude?: T;
      };
  story?: T;
  relatedPost?: T;
  relatedDestination?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photography-posts_select".
 */
export interface PhotographyPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  heroImage?: T;
  content?: T;
  excerpt?: T;
  publishedDate?: T;
  photoCategory?: T;
  tags?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  exifData?:
    | T
    | {
        camera?: T;
        lens?: T;
        settings?: T;
      };
  relatedPosts?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photo-galleries_select".
 */
export interface PhotoGalleriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  coverImage?: T;
  photos?:
    | T
    | {
        image?: T;
        caption?: T;
        location?: T;
        exif?:
          | T
          | {
              camera?: T;
              lens?: T;
              focalLength?: T;
              aperture?: T;
              shutterSpeed?: T;
              iso?: T;
            };
        id?: T;
      };
  destination?: T;
  gear?:
    | T
    | {
        camera?: T;
        lenses?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  exif?:
    | T
    | {
        camera?: T;
        lens?: T;
        aperture?: T;
        shutterSpeed?: T;
        iso?: T;
        focalLength?: T;
        takenAt?: T;
        latitude?: T;
        longitude?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  logo?: (number | null) | Media;
  socialLinks?: {
    instagram?: string | null;
    youtube?: string | null;
    tiktok?: string | null;
    pinterest?: string | null;
  };
  footerText?: string | null;
  defaultSeo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  items: {
    label: string;
    url: string;
    children?:
      | {
          label: string;
          url: string;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  logo?: T;
  socialLinks?:
    | T
    | {
        instagram?: T;
        youtube?: T;
        tiktok?: T;
        pinterest?: T;
      };
  footerText?: T;
  defaultSeo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        url?: T;
        children?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}